[workspace]
members = ["packages/*", "contracts/*"]

[profile.release.package.astro-nft]
opt-level = 3
debug = false
debug-assertions = false
codegen-units = 1
incremental = false

[profile.release.package.whitelist-airdrop]
rpath = false
lto = true
overflow-checks = true